//------------------------------------------------------------------------------
struct AppData
{
    float3 position   : POSITION;
    float3 normal     : NORMAL;
    float3 texcoord   : TEXCOORD0;
};

struct VertexOutput
{
    float4 position : POSITION;
    float3 texcoord : TEXCOORD0;
};
//------------------------------------------------------------------------------
VertexOutput main_vp( AppData           IN
                    , uniform float4    slice
                    , uniform float4x4  worldViewProj)
{

  VertexOutput OUT;
  OUT.position = mul(worldViewProj, float4(IN.position, 1));
  OUT.texcoord = float3(IN.texcoord.xy, slice.x);

  return OUT;
}

//------------------------------------------------------------------------------
void main_fp( float3            texcoord : TEXCOORD0
            , out float3        oColor   : COLOR
            , uniform sampler3D volume)
{
    oColor = tex3D(volume, texcoord);
}

//------------------------------------------------------------------------------
